Hw04
EvgeniaLeleo/sky-react-hw1 pull request #4
Opened 2022-06-05 18:07 UTC by EvgeniaLeleo

# Задание 1

 **Используя скелет компоненты, допишите код таймера до рабочего:** 
    - Исправьте ошибки.
    - В методах жизненных циклов определите взаимодействие с состоянием.
    - Повесьте события на кнопки. Допишите хендлеры.

```jsx
import React from 'react';
import './styles.css';

export default class ReacTimer extends React.Component {
    state = {
        count: 0,
        isCounting: false,
    };

    componentDidMount() {}

    componentDidUpdate() {}

    componentWillUnmount() {}

    render() {
        return (
            <div className="ReacTimer">
                <h1>React Timer</h1>
                <h3>{this.state.count}</h3>
                {!this.state.isCounting ? (
                    <button onClick={this.handleStart}>Start</button>
                ) : (
                    <button onClick={this.handleStop}>Stop</button>
                )}
                <button onClick={this.handleReset}>Reset</button>
            </div>
        );
    }
}
```
# Задание 2

 **Написать классовый компонент Часы.**
- Часы должны отображать реальное время и обновляться каждую секунду.
- Используйте методы жизненного цикла.
- Не забудьте очистить компонент перед размонтированием.

# Задание 3
 ⭐ (задача со звездочкой) **Написать компонент Pomodoro Tracker.**

- Компонент из 3х кнопок и отображения обратного отсчёта:
    
          Work Time - запускает таймер обратного отсчёта на 30 мин.
    

            Long Break - запускает таймер обратного отсчёта на 15 мин.

            Short Break - запускает таймер обратного отсчёта на 7 мин.

2022-06-06 09:08 UTC, mrerberg requested changes

2022-06-06 09:08 UTC, mrerberg commented on src/Reactimer.js
> +  componentDidMount() {}
Ты не смогла придумать наполнение для данного обработчика, так как запускаешь `handleStart` по кнопке. Если делать не по кнопке, то данная функция пригодится как раз

2022-06-06 09:08 UTC, mrerberg commented on src/Reactimer.js
> +            {Math.floor(value / interval / 60 / 60) % 24 < 10 ? 0 : ''}
Вынеси пожалуйста подобные преобразования в отдельные функции. К примеру, formatHour и тд

2022-06-06 09:08 UTC, mrerberg commented on src/Reactimer.js
> +            {Math.floor(value / interval / 60 / 60) % 24 < 10 ? 0 : ''}
Вынеси пожалуйста подобные преобразования в отдельные функции. К примеру, formatHour и тд

2022-06-06 15:27 UTC, mrerberg requested changes

2022-06-07 05:48 UTC, EvgeniaLeleo commented on src/Reactimer.js
> +            {Math.floor(value / interval / 60 / 60) % 24 < 10 ? 0 : ''}
+

2022-06-07 05:48 UTC, EvgeniaLeleo commented on src/Reactimer.js
> +            {Math.floor(value / interval / 60 / 60) % 24 < 10 ? 0 : ''}
Done

2022-06-07 05:49 UTC, EvgeniaLeleo commented on src/Reactimer.js
> +          <span>{this.formatHours()} : </span>
Done

2022-06-18 14:11 UTC, closed without merging