Hw06
EvgeniaLeleo/sky-react-hw1 pull request #6
Opened 2022-06-10 12:41 UTC by EvgeniaLeleo

# Задание

1. Доработать финальный пример с урока:
    - У каждого товара есть кнопка удаления из корзины.
    - Рассчитывается финальная стоимость заказа.
2. Реализовать пользовательский хук useInputRequired().
- Для этого написать отдельный компонент LoginPass, с двумя формами `<input>`

 Login Password соответственно. На которых и реализовать Hook с проверками.

- В данном хуке, помимо возвращаемого значения и функций изменения(`onChange`), на событие `onBlur` повесить логику обязательного/необязательного поля с возможностью передачи флага `required` вторым параметром хука. Ошибка должна храниться отдельным состоянием. То есть, если поле ввода будет пустым и не в фокусе, то возникнет предупреждение, что данное поле обязательно должно быть заполнено.

2022-06-11 14:49 UTC, mrerberg requested changes

2022-06-11 14:49 UTC, mrerberg commented on src/LoginPass.js
> +// import { useState } from 'react';
Мертвый код следует удалить

2022-06-11 14:49 UTC, mrerberg commented on src/LoginPass.js
> +  const loginStyle = `form-input ${
Это классы, loginStyles

https://www.npmjs.com/package/classnames

Рекомендую

2022-06-11 14:49 UTC, mrerberg commented on src/LoginPass.js
> +        {inputChangeHandle.errorText.login && (
Сделай деструкторизацию из inputChangeHandle объекта

```tsx
const { errorText } = inputChangeHandle;
```

2022-06-11 14:49 UTC, mrerberg commented on src/userHook.js
> +  const [value, setValue] = useState({ login: '', password: '' });
А почему в общем хуке для любых инпутов есть состояние с именами инпутов? login/password?

Мне кажется в данный хук как раз надо передавать название инпута и таким образом под каждый инпут делать свое состояние. Ты к другому инпуту (не логину, не паролю) не сможешь прикрепить данный хук

2022-06-11 15:12 UTC, EvgeniaLeleo commented on src/LoginPass.js
> +// import { useState } from 'react';
Done

2022-06-11 15:23 UTC, EvgeniaLeleo commented on src/LoginPass.js
> +  const loginStyle = `form-input ${
Done

2022-06-11 15:27 UTC, EvgeniaLeleo commented on src/LoginPass.js
> +        {inputChangeHandle.errorText.login && (
Done

2022-06-13 13:10 UTC, mrerberg requested changes

2022-06-13 13:10 UTC, mrerberg commented on src/components/LoginPass.js
> +          className={loginStyles}
Название переменных не очень подходящее. Это классы, а не стили

2022-06-13 13:10 UTC, mrerberg commented on src/components/LoginPass.js
> +          className={loginStyles}
Придирка

2022-06-13 17:50 UTC, EvgeniaLeleo commented on src/components/LoginPass.js
> +          className={loginStyles}
Done

2022-06-13 17:51 UTC, EvgeniaLeleo commented on src/components/LoginPass.js
> +    'border-red': state.email.errorText,
Полностью согласна. 
Done

2022-06-13 17:53 UTC, EvgeniaLeleo commented on src/components/LoginPass.js
> +    'border-red': state.email.errorText,
Done

2022-06-13 17:58 UTC, EvgeniaLeleo commented on src/components/userHook.js
> +          required: true,
Done

2022-06-18 14:12 UTC, closed without merging