Hw07
EvgeniaLeleo/sky-react-hw1 pull request #7
Opened 2022-06-11 12:20 UTC by EvgeniaLeleo

- Провести рефакторинг кода, используя возможности библиотеки PropTypes.
- Задача на повтор метода массива `.map()`:
    1. На следующем изображении четные числа выделены зеленым цветом, нечетные - желтым, а простые числа - красным. Создайте подобный отдельный компонент React. 
    - Изображение
        
        ![Безымянный.jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/022ced53-3700-48f0-b06b-2b0a9a19ee43/Безымянный.jpg)

2022-06-13 13:22 UTC, mrerberg requested changes

2022-06-13 13:22 UTC, mrerberg commented on src/App.js
> +      <p />
Может br?

2022-06-13 13:22 UTC, mrerberg commented on src/components/Book.js
> +  name: '<Unknown>',
Может просту пустую строку?

2022-06-13 13:22 UTC, mrerberg commented on src/components/NumbersTable.js
> +  const { n } = props
Что значит n? Неочевидное сокращение

2022-06-13 13:22 UTC, mrerberg commented on src/components/NumbersTable.js
> +  for (let i = 0; i < n; i += 1) {
Может это вынести в утилитарную функцию вне компонента? Она будет возвращать массив

2022-06-13 13:22 UTC, mrerberg commented on src/components/NumbersTable.js
> +          if (Number(el) % 2 === 0 && Number(el) !== 2) {
Эту проверку тоже можно вынести в отдельную функцию

2022-06-13 16:50 UTC, EvgeniaLeleo commented on src/App.js
> +      <p />
Вообще убрала. Там же везде дивы :)

2022-06-13 16:52 UTC, EvgeniaLeleo commented on src/components/Book.js
> +  name: '<Unknown>',
Тут спорный вопрос. Сделала пустую. Но с <Unknown> мне нравится больше

2022-06-13 16:54 UTC, EvgeniaLeleo commented on src/components/NumbersTable.js
> +  const { n } = props
Done

2022-06-13 17:15 UTC, EvgeniaLeleo commented on src/components/NumbersTable.js
> +  for (let i = 0; i < n; i += 1) {
Done

2022-06-14 07:58 UTC, mrerberg commented on src/components/Book.js
> +  name: '<Unknown>',
В рабочих моментах сделали бы пустую строку, а так я придрался)

2022-06-18 14:12 UTC, closed without merging